import { LfWord } from "../interfaces/lf-word";

export function WordsEn(): LfWord[]{

    return  [
{word:'aba', usedInGame:false},
{word:'abs', usedInGame:false},
{word:'ace', usedInGame:false},
{word:'act', usedInGame:true},
{word:'add', usedInGame:false},
{word:'ado', usedInGame:false},
{word:'aft', usedInGame:false},
{word:'age', usedInGame:false},
{word:'ago', usedInGame:false},
{word:'aha', usedInGame:false},
{word:'aid', usedInGame:false},
{word:'aim', usedInGame:true},
{word:'air', usedInGame:true},
{word:'ala', usedInGame:false},
{word:'ale', usedInGame:false},
{word:'all', usedInGame:false},
{word:'alt', usedInGame:false},
{word:'amp', usedInGame:false},
{word:'ana', usedInGame:false},
{word:'and', usedInGame:true},
{word:'ant', usedInGame:true},
{word:'any', usedInGame:true},
{word:'ape', usedInGame:true},
{word:'app', usedInGame:false},
{word:'apt', usedInGame:false},
{word:'arc', usedInGame:true},
{word:'are', usedInGame:true},
{word:'ark', usedInGame:true},
{word:'arm', usedInGame:true},
{word:'art', usedInGame:true},
{word:'ash', usedInGame:true},
{word:'ask', usedInGame:true},
{word:'asp', usedInGame:false},
{word:'ass', usedInGame:false},
{word:'ate', usedInGame:true},
{word:'ave', usedInGame:false},
{word:'awe', usedInGame:true},
{word:'axe', usedInGame:true},
{word:'aye', usedInGame:false},
{word:'baa', usedInGame:false},
{word:'bad', usedInGame:true},
{word:'bag', usedInGame:true},
{word:'ban', usedInGame:true},
{word:'bar', usedInGame:true},
{word:'bat', usedInGame:true},
{word:'bay', usedInGame:true},
{word:'bed', usedInGame:true},
{word:'bee', usedInGame:false},
{word:'beg', usedInGame:false},
{word:'bel', usedInGame:false},
{word:'ben', usedInGame:false},
{word:'bet', usedInGame:true},
{word:'bid', usedInGame:true},
{word:'big', usedInGame:true},
{word:'bin', usedInGame:true},
{word:'bio', usedInGame:true},
{word:'bis', usedInGame:false},
{word:'bit', usedInGame:false},
{word:'biz', usedInGame:false},
{word:'bob', usedInGame:false},
{word:'bog', usedInGame:true},
{word:'boo', usedInGame:false},
{word:'bow', usedInGame:true},
{word:'box', usedInGame:true},
{word:'boy', usedInGame:true},
{word:'bra', usedInGame:true},
{word:'bud', usedInGame:true},
{word:'bug', usedInGame:true},
{word:'bum', usedInGame:true},
{word:'bun', usedInGame:true},
{word:'bus', usedInGame:true},
{word:'but', usedInGame:true},
{word:'buy', usedInGame:true},
{word:'bye', usedInGame:true},
{word:'cab', usedInGame:true},
{word:'cad', usedInGame:false},
{word:'cam', usedInGame:false},
{word:'can', usedInGame:true},
{word:'cap', usedInGame:true},
{word:'car', usedInGame:true},
{word:'cat', usedInGame:true},
{word:'chi', usedInGame:false},
{word:'cob', usedInGame:true},
{word:'cod', usedInGame:true},
{word:'col', usedInGame:false},
{word:'con', usedInGame:true},
{word:'coo', usedInGame:false},
{word:'cop', usedInGame:true},
{word:'cor', usedInGame:false},
{word:'cos', usedInGame:false},
{word:'cot', usedInGame:true},
{word:'cow', usedInGame:false},
{word:'cox', usedInGame:false},
{word:'coy', usedInGame:true},
{word:'cry', usedInGame:true},
{word:'cub', usedInGame:false},
{word:'cue', usedInGame:false},
{word:'cup', usedInGame:true},
{word:'cut', usedInGame:true},
{word:'dab', usedInGame:true},
{word:'dad', usedInGame:true},
{word:'dal', usedInGame:false},
{word:'dam', usedInGame:true},
{word:'day', usedInGame:true},
{word:'dee', usedInGame:false},
{word:'def', usedInGame:false},
{word:'del', usedInGame:false},
{word:'den', usedInGame:true},
{word:'dew', usedInGame:true},
{word:'did', usedInGame:true},
{word:'die', usedInGame:true},
{word:'dig', usedInGame:true},
{word:'dim', usedInGame:true},
{word:'din', usedInGame:true},
{word:'dip', usedInGame:true},
{word:'dis', usedInGame:false},
{word:'doc', usedInGame:false},
{word:'doe', usedInGame:true},
{word:'dog', usedInGame:true},
{word:'don', usedInGame:true},
{word:'dot', usedInGame:true},
{word:'dry', usedInGame:true},
{word:'dub', usedInGame:true},
{word:'due', usedInGame:true},
{word:'dug', usedInGame:true},
{word:'dun', usedInGame:false},
{word:'duo', usedInGame:true},
{word:'dye', usedInGame:true},
{word:'ear', usedInGame:true},
{word:'eat', usedInGame:false},
{word:'ebb', usedInGame:false},
{word:'ecu', usedInGame:false},
{word:'eft', usedInGame:false},
{word:'egg', usedInGame:true},
{word:'ego', usedInGame:true},
{word:'elf', usedInGame:true},
{word:'elm', usedInGame:true},
{word:'emu', usedInGame:true},
{word:'end', usedInGame:true},
{word:'era', usedInGame:true},
{word:'eta', usedInGame:false},
{word:'eve', usedInGame:true},
{word:'eye', usedInGame:true},
{word:'fab', usedInGame:true},
{word:'fad', usedInGame:true},
{word:'fan', usedInGame:true},
{word:'far', usedInGame:true},
{word:'fat', usedInGame:true},
{word:'fax', usedInGame:true},
{word:'fay', usedInGame:false},
{word:'fed', usedInGame:true},
{word:'fee', usedInGame:true},
{word:'fen', usedInGame:false},
{word:'few', usedInGame:true},
{word:'fig', usedInGame:true},
{word:'fin', usedInGame:true},
{word:'fir', usedInGame:true},
{word:'fit', usedInGame:true},
{word:'fix', usedInGame:true},
{word:'flu', usedInGame:true},
{word:'fly', usedInGame:true},
{word:'foe', usedInGame:true},
{word:'fog', usedInGame:true},
{word:'for', usedInGame:true},
{word:'fox', usedInGame:true},
{word:'fry', usedInGame:true},
{word:'fun', usedInGame:true},
{word:'fur', usedInGame:true},
{word:'gag', usedInGame:true},
{word:'gal', usedInGame:false},
{word:'gap', usedInGame:true},
{word:'gas', usedInGame:true},
{word:'gay', usedInGame:true},
{word:'gee', usedInGame:false},
{word:'gel', usedInGame:true},
{word:'gem', usedInGame:true},
{word:'get', usedInGame:true},
{word:'gig', usedInGame:true},
{word:'gin', usedInGame:true},
{word:'god', usedInGame:true},
{word:'got', usedInGame:true},
{word:'gum', usedInGame:true},
{word:'gun', usedInGame:true},
{word:'gut', usedInGame:true},
{word:'guy', usedInGame:true},
{word:'gym', usedInGame:true},
{word:'had', usedInGame:true},
{word:'ham', usedInGame:true},
{word:'has', usedInGame:true},
{word:'hat', usedInGame:true},
{word:'hay', usedInGame:true},
{word:'hem', usedInGame:true},
{word:'hen', usedInGame:true},
{word:'her', usedInGame:true},
{word:'hey', usedInGame:true},
{word:'hid', usedInGame:true},
{word:'him', usedInGame:true},
{word:'hip', usedInGame:true},
{word:'his', usedInGame:true},
{word:'hit', usedInGame:false},
{word:'hog', usedInGame:true},
{word:'hop', usedInGame:true},
{word:'hot', usedInGame:true},
{word:'how', usedInGame:true},
{word:'hub', usedInGame:true},
{word:'hue', usedInGame:true},
{word:'hug', usedInGame:true},
{word:'huh', usedInGame:false},
{word:'hum', usedInGame:true},
{word:'hut', usedInGame:true},
{word:'ice', usedInGame:true},
{word:'icy', usedInGame:true},
{word:'igg', usedInGame:false},
{word:'ill', usedInGame:true},
{word:'imp', usedInGame:true},
{word:'ink', usedInGame:true},
{word:'inn', usedInGame:true},
{word:'ion', usedInGame:true},
{word:'its', usedInGame:true},
{word:'ivy', usedInGame:true},
{word:'jam', usedInGame:true},
{word:'jar', usedInGame:true},
{word:'jaw', usedInGame:true},
{word:'jay', usedInGame:true},
{word:'jet', usedInGame:true},
{word:'job', usedInGame:true},
{word:'joe', usedInGame:false},
{word:'jog', usedInGame:true},
{word:'joy', usedInGame:true},
{word:'jug', usedInGame:true},
{word:'kay', usedInGame:false},
{word:'ken', usedInGame:false},
{word:'key', usedInGame:true},
{word:'kid', usedInGame:true},
{word:'kin', usedInGame:true},
{word:'kit', usedInGame:true},
{word:'lab', usedInGame:true},
{word:'lac', usedInGame:false},
{word:'lad', usedInGame:true},
{word:'lag', usedInGame:true},
{word:'lam', usedInGame:false},
{word:'lap', usedInGame:true},
{word:'law', usedInGame:true},
{word:'lax', usedInGame:true},
{word:'lay', usedInGame:true},
{word:'lea', usedInGame:true},
{word:'led', usedInGame:true},
{word:'lee', usedInGame:true},
{word:'leg', usedInGame:true},
{word:'let', usedInGame:true},
{word:'lib', usedInGame:false},
{word:'lid', usedInGame:true},
{word:'lie', usedInGame:true},
{word:'lip', usedInGame:true},
{word:'lit', usedInGame:true},
{word:'log', usedInGame:true},
{word:'lot', usedInGame:true},
{word:'low', usedInGame:true},
{word:'mac', usedInGame:false},
{word:'mad', usedInGame:true},
{word:'mag', usedInGame:false},
{word:'man', usedInGame:true},
{word:'map', usedInGame:true},
{word:'mar', usedInGame:true},
{word:'mas', usedInGame:false},
{word:'mat', usedInGame:true},
{word:'max', usedInGame:true},
{word:'may', usedInGame:true},
{word:'med', usedInGame:true},
{word:'meg', usedInGame:false},
{word:'men', usedInGame:true},
{word:'met', usedInGame:true},
{word:'mid', usedInGame:false},
{word:'mil', usedInGame:false},
{word:'mix', usedInGame:true},
{word:'mob', usedInGame:true},
{word:'mod', usedInGame:false},
{word:'mol', usedInGame:false},
{word:'mom', usedInGame:true},
{word:'mon', usedInGame:false},
{word:'mop', usedInGame:true},
{word:'mot', usedInGame:false},
{word:'mud', usedInGame:true},
{word:'mug', usedInGame:true},
{word:'mum', usedInGame:false},
{word:'nab', usedInGame:true},
{word:'nah', usedInGame:false},
{word:'nan', usedInGame:false},
{word:'nap', usedInGame:true},
{word:'nay', usedInGame:false},
{word:'neb', usedInGame:false},
{word:'net', usedInGame:true},


{word:'new', usedInGame:true},
{word:'nil', usedInGame:true},
{word:'nip', usedInGame:true},
{word:'nod', usedInGame:true},
{word:'nor', usedInGame:true},
{word:'not', usedInGame:true},


{word:'now', usedInGame:true},
{word:'nun', usedInGame:false},
{word:'nut', usedInGame:true},
{word:'oak', usedInGame:true},
{word:'odd', usedInGame:true},
{word:'off', usedInGame:true},
{word:'oft', usedInGame:true},
{word:'oil', usedInGame:true},
{word:'old', usedInGame:true},
{word:'ole', usedInGame:false},
{word:'one', usedInGame:true},
{word:'ooh', usedInGame:false},
{word:'opt', usedInGame:true},
{word:'orb', usedInGame:true},
{word:'ore', usedInGame:true},
{word:'our', usedInGame:true},
{word:'out', usedInGame:true},
{word:'owe', usedInGame:true},
{word:'owl', usedInGame:true},
{word:'own', usedInGame:true},
{word:'pac', usedInGame:false},
{word:'pad', usedInGame:true},
{word:'pal', usedInGame:true},
{word:'pam', usedInGame:false},
{word:'pan', usedInGame:true},
{word:'pap', usedInGame:false},
{word:'par', usedInGame:true},
{word:'pas', usedInGame:true},
{word:'pat', usedInGame:true},
{word:'paw', usedInGame:true},
{word:'pay', usedInGame:true},
{word:'pea', usedInGame:true},
{word:'peg', usedInGame:true},
{word:'pen', usedInGame:true},
{word:'pep', usedInGame:false},
{word:'per', usedInGame:true},
{word:'pet', usedInGame:true},
{word:'pew', usedInGame:true},
{word:'phi', usedInGame:false},
{word:'pic', usedInGame:false},
{word:'pie', usedInGame:true},
{word:'pig', usedInGame:true},
{word:'pin', usedInGame:true},
{word:'pip', usedInGame:false},
{word:'pit', usedInGame:true},
{word:'ply', usedInGame:true},
{word:'pod', usedInGame:true},
{word:'pol', usedInGame:false},
{word:'pop', usedInGame:false},
{word:'pot', usedInGame:false},
{word:'pro', usedInGame:false},
{word:'psi', usedInGame:false},
{word:'pub', usedInGame:false},
{word:'pup', usedInGame:false},
{word:'put', usedInGame:false},
{word:'rad', usedInGame:false},
{word:'rag', usedInGame:true},
{word:'raj', usedInGame:false},
{word:'ram', usedInGame:false},
{word:'ran', usedInGame:false},
{word:'rap', usedInGame:false},
{word:'rat', usedInGame:false},
{word:'raw', usedInGame:false},
{word:'ray', usedInGame:true},
{word:'red', usedInGame:false},
{word:'ref', usedInGame:false},
{word:'rem', usedInGame:false},


{word:'rep', usedInGame:false},
{word:'rev', usedInGame:false},
{word:'rib', usedInGame:true},
{word:'rid', usedInGame:true},
{word:'rig', usedInGame:true},
{word:'rim', usedInGame:true},
{word:'rip', usedInGame:true},
{word:'rob', usedInGame:true},
{word:'rod', usedInGame:true},
{word:'roe', usedInGame:true},
{word:'rot', usedInGame:true},
{word:'row', usedInGame:true},
{word:'rub', usedInGame:true},
{word:'rue', usedInGame:true},
{word:'rug', usedInGame:true},
{word:'rum', usedInGame:true},
{word:'run', usedInGame:true},
{word:'rye', usedInGame:true},
{word:'sab', usedInGame:false},
{word:'sac', usedInGame:false},
{word:'sad', usedInGame:true},
{word:'sag', usedInGame:true},
{word:'sal', usedInGame:false},
{word:'sap', usedInGame:true},
{word:'sat', usedInGame:true},
{word:'saw', usedInGame:true},
{word:'say', usedInGame:true},
{word:'sea', usedInGame:true},
{word:'sec', usedInGame:false},
{word:'see', usedInGame:true},
{word:'sen', usedInGame:false},
{word:'set', usedInGame:true},
{word:'sew', usedInGame:true},
{word:'sex', usedInGame:true},
{word:'she', usedInGame:true},
{word:'shy', usedInGame:true},
{word:'sic', usedInGame:false},
{word:'sim', usedInGame:false},
{word:'sin', usedInGame:true},
{word:'sip', usedInGame:true},
{word:'sir', usedInGame:true},
{word:'sis', usedInGame:false},
{word:'sit', usedInGame:true},
{word:'six', usedInGame:true},
{word:'ski', usedInGame:true},
{word:'sky', usedInGame:true},
{word:'sly', usedInGame:true},
{word:'sod', usedInGame:true},
{word:'sol', usedInGame:false},
{word:'son', usedInGame:true},
{word:'sow', usedInGame:true},
{word:'soy', usedInGame:true},
{word:'spa', usedInGame:true},
{word:'spy', usedInGame:true},
{word:'sub', usedInGame:true},
{word:'sue', usedInGame:true},
{word:'sum', usedInGame:true},
{word:'sun', usedInGame:true},
{word:'sup', usedInGame:true},
{word:'tab', usedInGame:true},
{word:'tad', usedInGame:true},
{word:'tag', usedInGame:true},
{word:'tam', usedInGame:false},
{word:'tan', usedInGame:true},
{word:'tap', usedInGame:true},
{word:'tar', usedInGame:true},
{word:'tat', usedInGame:false},
{word:'tax', usedInGame:true},
{word:'tea', usedInGame:true},
{word:'ted', usedInGame:false},
{word:'tee', usedInGame:true},
{word:'ten', usedInGame:true},
{word:'the', usedInGame:true},
{word:'thy', usedInGame:true},
{word:'tie', usedInGame:true},
{word:'tin', usedInGame:true},
{word:'tip', usedInGame:true},
{word:'tod', usedInGame:false},
{word:'toe', usedInGame:true},
{word:'tom', usedInGame:false},
{word:'ton', usedInGame:true},
{word:'too', usedInGame:true},
{word:'top', usedInGame:true},
{word:'tor', usedInGame:false},
{word:'tot', usedInGame:false},
{word:'tow', usedInGame:true},
{word:'toy', usedInGame:true},
{word:'try', usedInGame:true},
{word:'tub', usedInGame:true},
{word:'tug', usedInGame:true},
{word:'two', usedInGame:true},
{word:'use', usedInGame:true},
{word:'van', usedInGame:true},
{word:'vat', usedInGame:true},
{word:'vet', usedInGame:true},
{word:'via', usedInGame:true},
{word:'vie', usedInGame:true},
{word:'vow', usedInGame:true},
{word:'wan', usedInGame:true},
{word:'war', usedInGame:true},
{word:'was', usedInGame:true},
{word:'wax', usedInGame:true},
{word:'way', usedInGame:true},
{word:'web', usedInGame:true},
{word:'wed', usedInGame:true},
{word:'wee', usedInGame:true},
{word:'wet', usedInGame:false},
{word:'who', usedInGame:true},
{word:'why', usedInGame:true},
{word:'wig', usedInGame:true},
{word:'win', usedInGame:true},
{word:'wit', usedInGame:true},
{word:'won', usedInGame:true},
{word:'woo', usedInGame:false},
{word:'wow', usedInGame:true},
{word:'wry', usedInGame:true},
{word:'wye', usedInGame:true},
{word:'yen', usedInGame:true},
{word:'yep', usedInGame:true},
{word:'yes', usedInGame:true},
{word:'yet', usedInGame:true},
{word:'you', usedInGame:true},
{word:'zip', usedInGame:true},
{word:'zoo', usedInGame:false},
{'word':'azo','usedInGame':false},
{'word':'awn','usedInGame':false},
{'word':'awl','usedInGame':false},
{'word':'awa','usedInGame':false},
{'word':'ava','usedInGame':false},
{'word':'auk','usedInGame':false},
{'word':'att','usedInGame':false},
{'word':'ars','usedInGame':false},
{'word':'arf','usedInGame':false},
{'word':'arb','usedInGame':false},
{'word':'ani','usedInGame':false},
{'word':'ane','usedInGame':false},
{'word':'amu','usedInGame':false},
{'word':'ami','usedInGame':false},
{'word':'ama','usedInGame':false},
{'word':'alp','usedInGame':false},
{'word':'alb','usedInGame':false},
{'word':'ait','usedInGame':false},
{'word':'ain','usedInGame':false},
{'word':'ail','usedInGame':false},
{'word':'ahi','usedInGame':false},
{'word':'aga','usedInGame':false},
{'word':'adz','usedInGame':false},
{'word':'ads','usedInGame':false},
{'word':'aby','usedInGame':false},
{'word':'aal','usedInGame':false},
{'word':'aah','usedInGame':false},
{'word':'bys','usedInGame':false},
{'word':'bur','usedInGame':false},
{'word':'Bug','usedInGame':false},
{'word':'brr','usedInGame':false},
{'word':'bro','usedInGame':false},
{'word':'bos','usedInGame':false},
{'word':'bop','usedInGame':false},
{'word':'bod','usedInGame':false},
{'word':'boa','usedInGame':false},
{'word':'bib','usedInGame':false},
{'word':'bey','usedInGame':false},
{'word':'bas','usedInGame':false},
{'word':'bap','usedInGame':false},
{'word':'bam','usedInGame':false},
{'word':'bah','usedInGame':false},
{'word':'BAA','usedInGame':false},
{'word':'cwm','usedInGame':false},
{'word':'cur','usedInGame':false},
{'word':'cum','usedInGame':false},
{'word':'cru','usedInGame':false},
{'word':'coz','usedInGame':false},
{'word':'cog','usedInGame':false},
{'word':'cis','usedInGame':false},
{'word':'cep','usedInGame':false},
{'word':'cel','usedInGame':false},
{'word':'cee','usedInGame':false},
{'word':'cay','usedInGame':false},
{'word':'caw','usedInGame':false},
{'word':'dup','usedInGame':false},
{'word':'dum','usedInGame':false},
{'word':'dui','usedInGame':false},
{'word':'duh','usedInGame':false},
{'word':'dow','usedInGame':false},
{'word':'dos','usedInGame':false},
{'word':'dor','usedInGame':false},
{'word':'dom','usedInGame':false},
{'word':'dol','usedInGame':false},
{'word':'doh','usedInGame':false},
{'word':'dit','usedInGame':false},
{'word':'dif','usedInGame':false},
{'word':'dib','usedInGame':false},
{'word':'dey','usedInGame':false},
{'word':'dex','usedInGame':false},
{'word':'Dee','usedInGame':false},
{'word':'deb','usedInGame':false},
{'word':'daw','usedInGame':false},
{'word':'dan','usedInGame':false},
{'word':'dak','usedInGame':false},
{'word':'dah','usedInGame':false},
{'word':'dag','usedInGame':false},
{'word':'ewe','usedInGame':false},
{'word':'ess','usedInGame':false},
{'word':'ers','usedInGame':false},
{'word':'err','usedInGame':false},
{'word':'ern','usedInGame':false},
{'word':'erg','usedInGame':false},
{'word':'ere','usedInGame':false},
{'word':'eon','usedInGame':false},
{'word':'ens','usedInGame':false},
{'word':'eng','usedInGame':false},
{'word':'ems','usedInGame':false},
{'word':'emo','usedInGame':false},
{'word':'eme','usedInGame':false},
{'word':'ell','usedInGame':false},
{'word':'elk','usedInGame':false},
{'word':'eld','usedInGame':false},
{'word':'efs','usedInGame':false},
{'word':'eff','usedInGame':false},
{'word':'eel','usedInGame':false},
{'word':'eek','usedInGame':false},
{'word':'eco','usedInGame':false},
{'word':'eau','usedInGame':false},
{'word':'fug','usedInGame':false},
{'word':'fub','usedInGame':false},
{'word':'fro','usedInGame':false},
{'word':'foy','usedInGame':false},
{'word':'fou','usedInGame':false},
{'word':'foo','usedInGame':false},
{'word':'fon','usedInGame':false},
{'word':'foh','usedInGame':false},
{'word':'fob','usedInGame':false},
{'word':'fil','usedInGame':false},
{'word':'fie','usedInGame':false},
{'word':'fid','usedInGame':false},
{'word':'fez','usedInGame':false},
{'word':'fey','usedInGame':false},
{'word':'feu','usedInGame':false},
{'word':'fet','usedInGame':false},
{'word':'fer','usedInGame':false},
{'word':'fem','usedInGame':false},
{'word':'fas','usedInGame':false},
{'word':'fah','usedInGame':false},
{'word':'gul','usedInGame':false},
{'word':'goy','usedInGame':false},
{'word':'gox','usedInGame':false},
{'word':'goo','usedInGame':false},
{'word':'gob','usedInGame':false},
{'word':'goa','usedInGame':false},
{'word':'gnu','usedInGame':false},
{'word':'gis','usedInGame':false},
{'word':'gip','usedInGame':false},
{'word':'gie','usedInGame':false},
{'word':'gid','usedInGame':false},
{'word':'ghi','usedInGame':false},
{'word':'gey','usedInGame':false},
{'word':'gen','usedInGame':false},
{'word':'ged','usedInGame':false},
{'word':'gat','usedInGame':false},
{'word':'gan','usedInGame':false},
{'word':'gam','usedInGame':false},
{'word':'gad','usedInGame':false},
{'word':'gab','usedInGame':false},
{'word':'hup','usedInGame':false},
{'word':'hun','usedInGame':false},
{'word':'hoy','usedInGame':false},
{'word':'hon','usedInGame':false},
{'word':'hom','usedInGame':false},
{'word':'hod','usedInGame':false},
{'word':'hob','usedInGame':false},
{'word':'hmm','usedInGame':false},
{'word':'hie','usedInGame':false},
{'word':'hic','usedInGame':false},
{'word':'hex','usedInGame':false},
{'word':'het','usedInGame':false},
{'word':'hes','usedInGame':false},
{'word':'hep','usedInGame':false},
{'word':'haw','usedInGame':false},
{'word':'hap','usedInGame':false},
{'word':'hao','usedInGame':false},
{'word':'hah','usedInGame':false},
{'word':'hag','usedInGame':false},
{'word':'hae','usedInGame':false},
{'word':'ism','usedInGame':false},
{'word':'irk','usedInGame':false},
{'word':'ire','usedInGame':false},
{'word':'ins','usedInGame':false},
{'word':'ilk','usedInGame':false},
{'word':'ifs','usedInGame':false},
{'word':'ids','usedInGame':false},
{'word':'ick','usedInGame':false},
{'word':'ich','usedInGame':false},
{'word':'jut','usedInGame':false},
{'word':'jun','usedInGame':false},
{'word':'jow','usedInGame':false},
{'word':'jot','usedInGame':false},
{'word':'jig','usedInGame':false},
{'word':'jib','usedInGame':false},
{'word':'jew','usedInGame':false},
{'word':'jeu','usedInGame':false},
{'word':'jag','usedInGame':false},
{'word':'jab','usedInGame':false},
{'word':'kue','usedInGame':false},
{'word':'kos','usedInGame':false},
{'word':'kor','usedInGame':false},
{'word':'kop','usedInGame':false},
{'word':'koi','usedInGame':false},
{'word':'koa','usedInGame':false},
{'word':'kir','usedInGame':false},
{'word':'kip','usedInGame':false},
{'word':'kif','usedInGame':false},
{'word':'kex','usedInGame':false},
{'word':'kep','usedInGame':false},
{'word':'keg','usedInGame':false},
{'word':'kef','usedInGame':false},
{'word':'kea','usedInGame':false},
{'word':'kat','usedInGame':false},
{'word':'kas','usedInGame':false},
{'word':'kaf','usedInGame':false},
{'word':'kae','usedInGame':false},
{'word':'kab','usedInGame':false},
{'word':'lye','usedInGame':false},
{'word':'lux','usedInGame':false},
{'word':'luv','usedInGame':false},
{'word':'lug','usedInGame':false},
{'word':'lud','usedInGame':false},
{'word':'lox','usedInGame':false},
{'word':'lop','usedInGame':false},
{'word':'lob','usedInGame':false},
{'word':'lis','usedInGame':false},
{'word':'lin','usedInGame':false},
{'word':'ley','usedInGame':false},
{'word':'lev','usedInGame':false},
{'word':'leu','usedInGame':false},
{'word':'les','usedInGame':false},
{'word':'lek','usedInGame':false},
{'word':'lei','usedInGame':false},
{'word':'lav','usedInGame':false},
{'word':'las','usedInGame':false},
{'word':'lar','usedInGame':false},
{'word':'lah','usedInGame':false},
{'word':'mux','usedInGame':false},
{'word':'mut','usedInGame':false},
{'word':'mus','usedInGame':false},
{'word':'mun','usedInGame':false},
{'word':'mow','usedInGame':false},
{'word':'mos','usedInGame':false},
{'word':'mor','usedInGame':false},
{'word':'moo','usedInGame':false},
{'word':'moi','usedInGame':false},
{'word':'mog','usedInGame':false},
{'word':'moc','usedInGame':false},
{'word':'moa','usedInGame':false},
{'word':'mmm','usedInGame':false},
{'word':'mis','usedInGame':false},
{'word':'mir','usedInGame':false},
{'word':'mim','usedInGame':false},
{'word':'mig','usedInGame':false},
{'word':'mic','usedInGame':false},
{'word':'mib','usedInGame':false},
{'word':'mho','usedInGame':false},
{'word':'mew','usedInGame':false},
{'word':'Met','usedInGame':false},
{'word':'mem','usedInGame':false},
{'word':'mel','usedInGame':false},
{'word':'maw','usedInGame':false},
{'word':'mam','usedInGame':false},
{'word':'mae','usedInGame':false},
{'word':'nus','usedInGame':false},
{'word':'nub','usedInGame':false},
{'word':'nth','usedInGame':false},
{'word':'nos','usedInGame':false},
{'word':'noo','usedInGame':false},
{'word':'nom','usedInGame':false},
{'word':'noh','usedInGame':false},
{'word':'nog','usedInGame':false},
{'word':'nob','usedInGame':false},
{'word':'nix','usedInGame':false},
{'word':'nit','usedInGame':false},
{'word':'nim','usedInGame':false},
{'word':'nib','usedInGame':false},
{'word':'neg','usedInGame':false},
{'word':'nee','usedInGame':false},
{'word':'naw','usedInGame':false},
{'word':'nam','usedInGame':false},
{'word':'nag','usedInGame':false},
{'word':'nae','usedInGame':false},
{'word':'oxy','usedInGame':false},
{'word':'oxo','usedInGame':false},
{'word':'owt','usedInGame':false},
{'word':'ova','usedInGame':false},
{'word':'oud','usedInGame':false},
{'word':'ose','usedInGame':false},
{'word':'ort','usedInGame':false},
{'word':'ors','usedInGame':false},
{'word':'orc','usedInGame':false},
{'word':'ora','usedInGame':false},
{'word':'ops','usedInGame':false},
{'word':'ope','usedInGame':false},
{'word':'oot','usedInGame':false},
{'word':'oof','usedInGame':false},
{'word':'ons','usedInGame':false},
{'word':'ono','usedInGame':false},
{'word':'oms','usedInGame':false},
{'word':'oke','usedInGame':false},
{'word':'oka','usedInGame':false},
{'word':'oik','usedInGame':false},
{'word':'ohs','usedInGame':false},
{'word':'oho','usedInGame':false},
{'word':'ohm','usedInGame':false},
{'word':'oes','usedInGame':false},
{'word':'ods','usedInGame':false},
{'word':'ode','usedInGame':false},
{'word':'oda','usedInGame':false},
{'word':'och','usedInGame':false},
{'word':'oca','usedInGame':false},
{'word':'obi','usedInGame':false},
{'word':'obe','usedInGame':false},
{'word':'oba','usedInGame':false},
{'word':'oat','usedInGame':false},
{'word':'oar','usedInGame':false},
{'word':'oaf','usedInGame':false},
{'word':'pyx','usedInGame':false},
{'word':'pye','usedInGame':false},
{'word':'pya','usedInGame':false},
{'word':'pus','usedInGame':false},
{'word':'pur','usedInGame':false},
{'word':'pun','usedInGame':false},
{'word':'pul','usedInGame':false},
{'word':'pug','usedInGame':false},
{'word':'pud','usedInGame':false},
{'word':'pry','usedInGame':false},
{'word':'pox','usedInGame':true},
{'word':'pow','usedInGame':false},
{'word':'pos','usedInGame':false},
{'word':'poo','usedInGame':false},
{'word':'pom','usedInGame':false},
{'word':'poi','usedInGame':false},
{'word':'poh','usedInGame':false},
{'word':'pix','usedInGame':false},
{'word':'piu','usedInGame':false},
{'word':'pis','usedInGame':false},
{'word':'pia','usedInGame':false},
{'word':'pht','usedInGame':false},
{'word':'pho','usedInGame':false},
{'word':'pes','usedInGame':false},
{'word':'peh','usedInGame':false},
{'word':'pee','usedInGame':false},
{'word':'ped','usedInGame':false},
{'word':'pec','usedInGame':false},
{'word':'pax','usedInGame':false},
{'word':'pah','usedInGame':false},
{'word':'ryu','usedInGame':false},
{'word':'rya','usedInGame':false},
{'word':'rut','usedInGame':false},
{'word':'roo','usedInGame':false},
{'word':'rom','usedInGame':false},
{'word':'roc','usedInGame':false},
{'word':'rin','usedInGame':false},
{'word':'rif','usedInGame':false},
{'word':'ria','usedInGame':false},
{'word':'rho','usedInGame':false},
{'word':'rex','usedInGame':false},
{'word':'ret','usedInGame':false},
{'word':'res','usedInGame':false},
{'word':'rei','usedInGame':false},
{'word':'reg','usedInGame':false},
{'word':'ree','usedInGame':false},
{'word':'rec','usedInGame':false},
{'word':'reb','usedInGame':false},
{'word':'rax','usedInGame':false},
{'word':'ras','usedInGame':false},
{'word':'rai','usedInGame':false},
{'word':'rah','usedInGame':false},
{'word':'qua','usedInGame':false},
{'word':'qis','usedInGame':false},
{'word':'qat','usedInGame':false},
{'word':'syn','usedInGame':false},
{'word':'sus','usedInGame':false},
{'word':'suq','usedInGame':false},
{'word':'suk','usedInGame':false},
{'word':'sty','usedInGame':false},
{'word':'sri','usedInGame':false},
{'word':'sox','usedInGame':false},
{'word':'sou','usedInGame':false},
{'word':'sot','usedInGame':false},
{'word':'sos','usedInGame':false},
{'word':'sop','usedInGame':false},
{'word':'som','usedInGame':false},
{'word':'soh','usedInGame':false},
{'word':'soc','usedInGame':false},
{'word':'sob','usedInGame':false},
{'word':'ska','usedInGame':false},
{'word':'sib','usedInGame':false},
{'word':'sho','usedInGame':false},
{'word':'shh','usedInGame':false},
{'word':'sha','usedInGame':false},
{'word':'sez','usedInGame':false},
{'word':'sev','usedInGame':false},
{'word':'ser','usedInGame':false},
{'word':'sel','usedInGame':false},
{'word':'sei','usedInGame':false},
{'word':'sax','usedInGame':false},
{'word':'sau','usedInGame':false},
{'word':'san','usedInGame':false},
{'word':'sae','usedInGame':false},
{'word':'tye','usedInGame':false},
{'word':'twa','usedInGame':false},
{'word':'tux','usedInGame':false},
{'word':'tut','usedInGame':false},
{'word':'tup','usedInGame':false},
{'word':'tun','usedInGame':false},
{'word':'tum','usedInGame':false},
{'word':'tui','usedInGame':false},
{'word':'tsk','usedInGame':false},
{'word':'tog','usedInGame':false},
{'word':'tiz','usedInGame':false},
{'word':'tit','usedInGame':false},
{'word':'tis','usedInGame':false},
{'word':'til','usedInGame':false},
{'word':'tic','usedInGame':false},
{'word':'tho','usedInGame':false},
{'word':'tew','usedInGame':false},
{'word':'tet','usedInGame':false},
{'word':'tel','usedInGame':false},
{'word':'teg','usedInGame':false},
{'word':'taw','usedInGame':false},
{'word':'tav','usedInGame':false},
{'word':'tau','usedInGame':false},
{'word':'tas','usedInGame':false},
{'word':'tao','usedInGame':false},
{'word':'taj','usedInGame':false},
{'word':'tae','usedInGame':false},
{'word':'uts','usedInGame':false},
{'word':'ute','usedInGame':false},
{'word':'uta','usedInGame':false},
{'word':'urn','usedInGame':false},
{'word':'urd','usedInGame':false},
{'word':'urb','usedInGame':false},
{'word':'ups','usedInGame':false},
{'word':'upo','usedInGame':false},
{'word':'uns','usedInGame':false},
{'word':'uni','usedInGame':false},
{'word':'ump','usedInGame':false},
{'word':'umm','usedInGame':false},
{'word':'ulu','usedInGame':false},
{'word':'uke','usedInGame':false},
{'word':'ugh','usedInGame':false},
{'word':'udo','usedInGame':false},
{'word':'vug','usedInGame':false},
{'word':'vox','usedInGame':false},
{'word':'vog','usedInGame':false},
{'word':'voe','usedInGame':false},
{'word':'vis','usedInGame':false},
{'word':'vin','usedInGame':false},
{'word':'vim','usedInGame':false},
{'word':'vig','usedInGame':false},
{'word':'vid','usedInGame':false},
{'word':'vex','usedInGame':false},
{'word':'veg','usedInGame':false},
{'word':'vee','usedInGame':false},
{'word':'vaw','usedInGame':false},
{'word':'vav','usedInGame':false},
{'word':'vau','usedInGame':false},
{'word':'vas','usedInGame':false},
{'word':'var','usedInGame':false},
{'word':'vac','usedInGame':false},
{'word':'wyn','usedInGame':false},
{'word':'wuz','usedInGame':false},
{'word':'wud','usedInGame':false},
{'word':'wot','usedInGame':false},
{'word':'wos','usedInGame':false},
{'word':'wok','usedInGame':false},
{'word':'woe','usedInGame':false},
{'word':'wiz','usedInGame':false},
{'word':'wha','usedInGame':false},
{'word':'wen','usedInGame':false},
{'word':'waw','usedInGame':false},
{'word':'wat','usedInGame':false},
{'word':'wap','usedInGame':false},
{'word':'wag','usedInGame':false},
{'word':'wae','usedInGame':false},
{'word':'wad','usedInGame':false},
{'word':'wab','usedInGame':false},
{'word':'xis','usedInGame':false},
{'word':'yup','usedInGame':false},
{'word':'yum','usedInGame':false},
{'word':'yuk','usedInGame':false},
{'word':'yow','usedInGame':false},
{'word':'yon','usedInGame':false},
{'word':'yom','usedInGame':false},
{'word':'yok','usedInGame':false},
{'word':'yod','usedInGame':false},
{'word':'yob','usedInGame':false},
{'word':'yip','usedInGame':false},
{'word':'yin','usedInGame':false},
{'word':'yez','usedInGame':false},
{'word':'yew','usedInGame':false},
{'word':'yer','usedInGame':false},
{'word':'yeh','usedInGame':false},
{'word':'yea','usedInGame':false},
{'word':'yay','usedInGame':false},
{'word':'yaw','usedInGame':false},
{'word':'yas','usedInGame':false},
{'word':'yar','usedInGame':false},
{'word':'yap','usedInGame':false},
{'word':'yam','usedInGame':true},
{'word':'yak','usedInGame':false},
{'word':'yah','usedInGame':false},
{'word':'yag','usedInGame':false},
{'word':'zoa','usedInGame':false},
{'word':'zit','usedInGame':false},
{'word':'zin','usedInGame':false},
{'word':'zig','usedInGame':false},
{'word':'zen','usedInGame':false},
{'word':'zek','usedInGame':false},
{'word':'zee','usedInGame':false},
{'word':'zed','usedInGame':false},
{'word':'zax','usedInGame':false},
{'word':'zas','usedInGame':false},
{'word':'zap','usedInGame':true},
{'word':'zag','usedInGame':false}



]};